# SOME DESCRIPTIVE TITLE.
# Copyright (C) 2018, NEM
# This file is distributed under the same license as the nem2-docs package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
# 
# Translators:
# Yoshiyuki Ieyama, 2019
# 
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: nem2-docs 0.14.1\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2019-01-16 07:27+0900\n"
"PO-Revision-Date: 2018-10-26 13:40+0000\n"
"Last-Translator: Yoshiyuki Ieyama, 2019\n"
"Language-Team: Japanese (https://www.transifex.com/44uk-works/teams/92962/ja/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: ja\n"
"Plural-Forms: nplurals=1; plural=0;\n"

#: ../../source/api/status-errors.rst:3
msgid "Status Errors"
msgstr "ステータスエラー"

#: ../../source/api/status-errors.rst:5
msgid ""
"This section describes the error messages that can be returned via status "
"channel after announcing a transaction."
msgstr "このセクションでは、トランザクションをアナウンスした後に、ステータスチャンネルが返却するエラーメッセージの説明をします。"

#: ../../source/api/status-errors.rst:7
msgid ""
"Configuration parameters are `editable <https://github.com/nemtech/catapult-"
"server/blob/master/resources/config-network.properties>`_. Public network "
"configuration may differ."
msgstr ""
"設定パラメータは `編集可能 <https://github.com/nemtech/catapult-"
"server/blob/master/resources/config-network.properties>`_ "
"です。公開ネットワークでは異なる可能性があります。"

#: ../../source/api/status-errors.rst:1
msgid "Error code"
msgstr "エラーコード"

#: ../../source/api/status-errors.rst:1
msgid "Description"
msgstr "説明"

#: ../../source/api/status-errors.rst:1
msgid "Success"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Validation result is success."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Neutral"
msgstr "中立"

#: ../../source/api/status-errors.rst:1
msgid "Validation result is neither success nor failure."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure"
msgstr "失敗"

#: ../../source/api/status-errors.rst:1
msgid "Validation result is failure."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Core_Past_Deadline"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Validation failed because the deadline passed."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Core_Future_Deadline"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid ""
"Validation failed because the deadline is too far in the future. Deadlines "
"are only allowed to lie up to ``24`` hours ahead."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Core_Insufficient_Balance"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Validation failed because the account has an insufficient balance."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Core_Too_Many_Transactions"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Validation failed because there are too many transactions in a block."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Core_Nemesis_Account_Signed_After_Nemesis_Block"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid ""
"Validation failed because an entity originated from the nemesis account "
"after the nemesis block."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Core_Wrong_Network"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Validation failed because the entity has the wrong network specified."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Core_Invalid_Address"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Validation failed because an address is invalid."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Core_Block_Harvester_Ineligible"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid ""
"Validation failed because a block was harvested by an ineligible harvester"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Hash_Exists"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Validation failed because the entity hash is already known."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Signature_Not_Verifiable"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Validation failed because the verification of the signature failed."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Aggregate_Too_Many_Transactions"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid ""
"Validation failed because aggregate has too many transactions. An aggregate "
"transaction can contain up to ``1000`` inner transactions."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Aggregate_No_Transactions"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Validation failed because aggregate does not have any transactions."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Aggregate_Too_Many_Cosignatures"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid ""
"Validation failed because aggregate has too many cosignatures. The maximum "
"number of cosignatories allowed is ``15``."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Aggregate_Redundant_Cosignatures"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Validation failed because redundant cosignatures are present."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Aggregate_Ineligible_Cosigners"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Validation failed because at least one cosigner is ineligible."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Aggregate_Missing_Cosigners"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid ""
"Validation failed because at least one required cosigner is missing. The "
"tranaction was announced as complete but had missing cosignatures."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Lock_Invalid_Hash_Algorithm"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid ""
"Validation failed because hash algorithm for lock type secret is invalid. "
"See the :doc:`available algorithms <../concepts/cross-chain-swaps>` list."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Lock_Invalid_Mosaic_Id"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid ""
"Validation failed because lock does not allow the specified mosaic. The only"
" mosaic allowed is ``xem``."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Lock_Invalid_Mosaic_Amount"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid ""
"Validation failed because lock does not allow the specified amount. The "
"minimum amount is ``10``."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Lock_Hash_Exists"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Validation failed because hash is already present in cache."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Lock_Hash_Does_Not_Exist"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Validation failed because hash is not present in cache."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Lock_Missing_Secret_Padding"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Validation failed because hash is not 0 padded."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Lock_Hash_Not_Implemented"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Validation failed because hash is not implemented yet."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Lock_Proof_Size_Out_Of_Bounds"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid ""
"Validation failed because proof is too small or too large. It should be "
"between ``10 and 1000 bytes``."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Lock_Secret_Mismatch"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Validation failed because secret does not match proof."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Lock_Unknown_Secret"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Validation failed because secret is unknown."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Lock_Inactive_Hash"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Validation failed because hash is inactive."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Lock_Inactive_Secret"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Validation failed because secret is inactive."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Lock_Hash_Algorithm_Mismatch"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Validation failed because hash algorithm does not match."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Lock_Hash_Already_Used"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Validation failed because hash has already been used."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Lock_Secret_Already_Used"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Validation failed because secret has already been used."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Lock_Invalid_Duration"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Validation failed because duration is too long."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Multisig_Modify_Account_In_Both_Sets"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid ""
"Validation failed because account is specified to be both added and removed."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Multisig_Modify_Multiple_Deletes"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Validation failed because multiple removals are present."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Multisig_Modify_Redundant_Modifications"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Validation failed because redundant modifications are present."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Multisig_Modify_Unknown_Multisig_Account"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Validation failed because account is not in multisig cache."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Multisig_Modify_Not_A_Cosigner"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Validation failed because account to be removed is not present."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Multisig_Modify_Already_A_Cosigner"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid ""
"Validation failed because account to be added is already a cosignatory."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Multisig_Modify_Min_Setting_Out_Of_Range"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Validation failed because new minimum settings are out of range."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Multisig_Modify_Min_Setting_Larger_Than_Num_Cosignatories"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid ""
"Validation failed because min settings are larger than number of "
"cosignatories."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Multisig_Modify_Unsupported_Modification_Type"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid ""
"Validation failed because the modification type is unsupported: add (0) and "
"remove (1)."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Multisig_Modify_Max_Cosigned_Accounts"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid ""
"Validation failed because the cosignatory already cosigns the maximum number"
" of accounts. An account cannot be cosignatory of more than ``5`` multisig "
"accounts."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Multisig_Modify_Max_Cosigners"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid ""
"Validation failed because the multisig account already has the maximum "
"number of cosignatories. A multisig account cannot have more than ``10`` "
"cosignatories."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Multisig_Modify_Loop"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid ""
"Validation failed because a multisig loop is created. A multisig account "
"cannot be cosignatory of itself. Neither an account can be turned into "
"multisig having as cosignatory another multisig where the account is "
"cosignatory."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Multisig_Modify_Max_Multisig_Depth"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid ""
"Validation failed because the max multisig depth is exceeded. The maximum "
"depth of a multilevel multisig account is ``3``."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Multisig_Operation_Not_Permitted_By_Account"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid ""
"Validation failed because an operation is not permitted by a multisig "
"account. A multisig account cannot be converted into a multisig account "
"again."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Mosaic_Invalid_Name"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid ""
"Validation failed because the name is invalid. The mosaic name may have a "
"maximum length of ``64`` characters. Allowed characters are `a-to-z`; "
"`0-to-9` and the following special characters: \\`_-"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Namespace_Invalid_Duration"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid ""
"Validation failed because the duration has an invalid value. Duration is "
"allowed to lie up to ``365`` days."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Mosaic_Invalid_Duration"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid ""
"Validation failed because the name is invalid. Duration is allowed to lie up"
" to ``365`` days."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Mosaic_Name_Id_Mismatch"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Validation failed because the name and id don't match."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Namespace_Expired"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Validation failed because the parent is expired."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Mosaic_Owner_Conflict"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid ""
"Validation failed because the parent owner conflicts with the child owner."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Namespace_Invalid_Namespace_Type"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Validation failed because the namespace type is invalid."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Namespace_Root_Name_Reserved"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid ""
"Validation failed because the root namespace has a `reserved name "
"<https://github.com/nemtech/catapult-server/blob/master/resources/config-"
"network.properties#L60>`_."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Namespace_Too_Deep"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid ""
"Validation failed because the resulting namespace would exceed the maximum "
"allowed namespace depth. Namespaces can have up to ``3`` nested levels."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Namespace_Parent_Unknown"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Validation failed because the namespace parent is unknown."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Namespace_Already_Exists"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Validation failed because the namespace already exists."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Namespace_Already_Active"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Validation failed because the namespace is already active."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Namespace_Eternal_After_Nemesis_Block"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid ""
"Validation failed because an eternal namespace was received after the "
"nemesis block."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Namespace_Max_Children_Exceeded"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid ""
"Validation failed because the maximum number of children for a root "
"namespace was exceeded."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Mosaic_Parent_Id_Conflict"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid ""
"Validation failed because the existing parent id does not match the supplied"
" parent id."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Mosaic_Invalid_Property"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Validation failed because a mosaic property is invalid."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Mosaic_Invalid_Flags"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Validation failed because the mosaic flags are invalid."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Mosaic_Invalid_Divisibility"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid ""
"Validation failed because the mosaic divisibility is invalid. It is greater "
"than ``6`` or negative."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Mosaic_Invalid_Supply_Change_Direction"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid ""
"Validation failed because the mosaic supply change direction is invalid: "
"decrease (0) and  increase (1)."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Mosaic_Invalid_Supply_Change_Amount"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Validation failed because the mosaic supply change amount is invalid."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Mosaic_Name_Reserved"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Validation failed because the mosaic has a reserved name."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Mosaic_Modification_Disallowed"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Validation failed because mosaic modification is not allowed."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Mosaic_Modification_No_Changes"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid ""
"Validation failed because mosaic modification would not result in any "
"changes."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Mosaic_Supply_Immutable"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Validation failed because the mosaic supply is immutable."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Mosaic_Supply_Negative"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Validation failed because the resulting mosaic supply is negative."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Mosaic_Supply_Exceeded"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid ""
"Validation failed because the resulting mosaic supply exceeds the maximum "
"allowed value. The range is between 0 and ``9.000.000.000``."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Mosaic_Non_Transferable"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Validation failed because the mosaic is not transferable."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Mosaic_Max_Mosaics_Exceeded"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid ""
"Validation failed because the credit of the mosaic would exceed the maximum "
"of different mosaics an account is allowed to own."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Transfer_Message_Too_Large"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "The message for the transaction exceeds the limit of ``1024`` bytes."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Transfer_Out_Of_Order_Mosaics"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Mosaics on a transfer transaction should be ordered by id value."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Chain_Unlinked"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid ""
"Validation failed because a block was received that did not link with the "
"existing chain."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Chain_Block_Not_Hit"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Validation failed because a block was received that is not a hit."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Consumer_Empty_Input"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Validation failed because the consumer input is empty."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Consumer_Block_Transactions_Hash_Mismatch"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid ""
"Validation failed because the block transactions hash does not match the "
"calculated value."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Consumer_Hash_In_Recency_Cache"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid ""
"Validation failed because an entity hash is present in the recency cache."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Consumer_Remote_Chain_Too_Many_Blocks"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Validation failed because the chain part has too many blocks."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Consumer_Remote_Chain_Improper_Link"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Validation failed because the chain is internally improperly linked."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Consumer_Remote_Chain_Duplicate_Transactions"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid ""
"Validation failed because the chain part contains duplicate transactions."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Consumer_Remote_Chain_Unlinked"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid ""
"Validation failed because the chain part does not link to the current chain."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Consumer_Remote_Chain_Mismatched_Difficulties"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid ""
"Validation failed because the remote chain difficulties do not match the "
"calculated difficulties."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Consumer_Remote_Chain_Score_Not_Better"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Validation failed because the remote chain score is not better."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Consumer_Remote_Chain_Too_Far_Behind"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Validation failed because the remote chain is too far behind."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Extension_Partial_Transaction_Cache_Prune"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid ""
"Validation failed because the partial transaction was pruned from the "
"temporal cache."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Extension_Partial_Transaction_Dependency_Removed"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid ""
"Validation failed because the partial transaction was pruned from the "
"temporal cache due to its dependency being removed."
msgstr ""
