# SOME DESCRIPTIVE TITLE.
# Copyright (C) 2018, NEM
# This file is distributed under the same license as the nem2-docs package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
# 
# Translators:
# Yoshiyuki Ieyama, 2018
# 
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: nem2-docs 0.13\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2018-11-05 12:47+0900\n"
"PO-Revision-Date: 2018-10-26 13:40+0000\n"
"Last-Translator: Yoshiyuki Ieyama, 2018\n"
"Language-Team: Japanese (https://www.transifex.com/44uk-works/teams/92962/ja/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: ja\n"
"Plural-Forms: nplurals=1; plural=0;\n"

#: ../../source/api/status-errors.rst:3
msgid "Status Errors"
msgstr "ステータスエラー"

#: ../../source/api/status-errors.rst:5
msgid ""
"This section describes the error messages that can be returned via status "
"channel after announcing a transaction."
msgstr "このセクションでは、トランザクションをアナウンスした後に、ステータスチャンネルが返却するエラーメッセージの説明をします。"

#: ../../source/api/status-errors.rst:7
msgid ""
"Configuration parameters are `editable <https://github.com/nemtech/catapult-"
"server/blob/master/resources/config-network.properties>`_. Public network "
"configuration may differ."
msgstr ""
"設定パラメータは `編集可能 <https://github.com/nemtech/catapult-"
"server/blob/master/resources/config-network.properties>`_ "
"です。公開ネットワークでは異なる可能性があります。"

#: ../../source/api/status-errors.rst:1
msgid "Error code"
msgstr "エラーコード"

#: ../../source/api/status-errors.rst:1
msgid "Description"
msgstr "説明"

#: ../../source/api/status-errors.rst:1
msgid "Neutral"
msgstr "中立"

#: ../../source/api/status-errors.rst:1
msgid "Failure"
msgstr "失敗"

#: ../../source/api/status-errors.rst:1
msgid "Failure_Core_Past_Deadline"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid ""
"The deadline lies too far in the future. Deadlines are only allowed to lie "
"up to `24` hours ahead."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Core_Future_Deadline"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "The deadline lies in the past."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Core_Insufficient_Balance"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "The account does not have enough funds."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Core_Timestamp_Too_Far_In_Future"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "The timestamp of the entity lies too far in the future."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Core_Too_Many_Transactions"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Core_Nemesis_Account_Signed_After_Nemesis_Block"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid ""
"The supplied transaction has the nemesis account as the sender and cannot be"
" included in a normal block."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Core_Wrong_Network"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "The entity was rejected because it has the wrong network specified."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Core_Invalid_Address"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "An account specified in the request is not valid."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Core_Block_Harvester_Ineligible"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Hash_Exists"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid ""
"The hash of the entity already exists either in the cache or the database."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Signature_Not_Verifiable"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "The signature of the entity failed upon verification."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Aggregate_Too_Many_Transactions"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid ""
"The aggregate transaction exceeds the maximum number of inner transactions. "
"An aggregate transaction can contain up to ``1000`` inner transactions."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Aggregate_No_Transactions"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "The aggregate transaction does not contain any inner transactions."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Aggregate_Too_Many_Cosignatures"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid ""
"The aggregate transaction contains too many cosignatories. The maximum "
"number of cosignatories allowed is ``15``."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Aggregate_Redundant_Cosignatures"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid ""
"The aggregate transaction contains the cosignature of the account who signed"
" the transaction."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Aggregate_Ineligible_Cosigners"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid ""
"The account who signed the aggregate transaction is not an eligible "
"cosigner."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Aggregate_Missing_Cosigners"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid ""
"The aggregate transaction was announced as complete but there are missing "
"signatures."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Lock_Invalid_Hash_Algorithm"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "The hash algorithm used is not defined."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Lock_Invalid_Mosaic_Id"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "The locks funds transaction failed because locked mosaic is not XEM."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Lock_Invalid_Mosaic_Amount"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid ""
"The amount of locked XEM is insufficient. The minimum amount is ``10``."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Lock_Hash_Exists"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid ""
"The locks funds transaction failed because the hash of the aggregate "
"transaction already exists either in the cache or in the database."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Lock_Hash_Does_Not_Exist"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid ""
"The aggregate transaction failed because its hash has not been locked "
"previously."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Lock_Missing_Secret_Padding"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Lock_Hash_Not_Implemented"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "The secret lock and the secret proof hash algorithm used is different."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Lock_Proof_Size_Out_Of_Bounds"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid ""
"The proof length is invalid. It should be between ``10 and 1000 bytes``."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Lock_Secret_Mismatch"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "The proof hashed does not equal to the secret."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Lock_Unknown_Secret"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid ""
"The secret proof transaction specifies a secret that has not been found in "
"the cache."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Lock_Inactive_Hash"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid ""
"The aggregate bonded transaction has been sent after the secret lock funds "
"transactions for this hash expired."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Lock_Inactive_Secret"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid ""
"The secret proof transaction has been sent after the secret lock transaction"
" expired."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Lock_Hash_Algorithm_Mismatch"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Lock_Hash_Already_Used"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid ""
"The lock funds transaction failed because the aggregate transaction hash has"
" already been locked."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Lock_Secret_Already_Used"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid ""
"The secret lock transaction failed because the hash has already been used."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Lock_Invalid_Duration"
msgstr ""

#: ../../source/api/status-errors.rst:1 ../../source/api/status-errors.rst:1
#: ../../source/api/status-errors.rst:1
msgid ""
"Duration lies too far in the future or refers to past. Duration is allowed "
"to lie up to ``N`` blocks in the future."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Multisig_Modify_Account_In_Both_Sets"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid ""
"Adding and removing the same account in a single transaction is not "
"possible."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Multisig_Modify_Multiple_Deletes"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "It is not possible to remove multiple cosignatories at once."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Multisig_Modify_Redundant_Modifications"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "The transaction tried to add the same cosignatory more than once."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Multisig_Modify_Unknown_Multisig_Account"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid ""
"The multisig has not been created yet and the transaction includes a delete "
"modification."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Multisig_Modify_Not_A_Cosigner"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid ""
"The account who signed the transaction is not a cosignatory of the multisig "
"account."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Multisig_Modify_Already_A_Cosigner"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "A cosignatory added is already cosignatory of that multisig account."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Multisig_Modify_Min_Setting_Out_Of_Range"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid ""
"Multisig modification parameters are negative and inferior to the number of "
"cosignatories of the multisig."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Multisig_Modify_Min_Setting_Larger_Than_Num_Cosignatories"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid ""
"It is not possible to set more required signatures than cosignatories has "
"the multisig."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Multisig_Modify_Unsupported_Modification_Type"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "The modification type is different than add (0) or remove (1)."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Multisig_Modify_Max_Cosigned_Accounts"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "An account cannot be cosignatory of more than `5` multisig accounts."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Multisig_Modify_Max_Cosigners"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "A multisig account cannot have more than `10` cosignatories."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Multisig_Modify_Loop"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid ""
"A multisig account cannot be cosignatory of itself. Neither an account can "
"be turned into multisig having as cosignatory another multisig where the "
"account is cosignatory."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Multisig_Modify_Max_Multisig_Depth"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "The maximum depth of a multilevel multisig account is `3`."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Multisig_Operation_Not_Permitted_By_Account"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "A multisig account cannot be converted into a multisig account again."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Namespace_Invalid_Duration"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Mosaic_Invalid_Duration"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Namespace_Invalid_Name"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "The namespace name is invalid. See namespace."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Mosaic_Invalid_Name"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "The name for the mosaic is invalid. See mosaics."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Namespace_Name_Id_Mismatch"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Mosaic_Name_Id_Mismatch"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Namespace_Expired"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Validation failed because the namespace has expired."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Mosaic_Expired"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Validation failed because the mosaic has expired."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Namespace_Owner_Conflict"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "The signer of the transaction is not the owner of the namespace."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Mosaic_Owner_Conflict"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "The signer of the transaction is not the owner of the mosaic."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Namespace_Invalid_Namespace_Type"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid ""
"The namespace type is different than rootnamespace (0) or subnamesapce (1)."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Namespace_Root_Name_Reserved"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Certain strings are reserved and thus not allowed as namespace parts."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Namespace_Too_Deep"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Namespaces can have up to ``3`` levels."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Namespace_Parent_Unknown"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "The provided parent namespace is unknown."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Namespace_Already_Exists"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "The namespace already exists."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Namespace_Already_Active"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Namespace_Eternal_After_Nemesis_Block"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "The namespace duration is set to 0."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Mosaic_Parent_Id_Conflict"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Mosaic_Invalid_Property"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Transaction payload is invalid as it contains invalid property."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Mosaic_Invalid_Flags"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Transaction payload is invalid as it contains an invalid flag."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Mosaic_Invalid_Divisibility"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "The specified divisibility is greater than ``6`` or negative."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Mosaic_Invalid_Supply_Change_Direction"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid ""
"The supply change direction is different than decrease (0) or increase (1)."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Mosaic_Invalid_Supply_Change_Amount"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "The provided supply change amount is not greater than 0."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Mosaic_Name_Reserved"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Certain strings are reserved and thus not allowed as mosaic parts."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Mosaic_Modification_Disallowed"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Mosaic_Modification_No_Changes"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid ""
"Mosaic modification transaction did not alter the mosaic as it has the same "
"definition."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Mosaic_Supply_Immutable"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Validation failed because the mosaic supply is immutable."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Mosaic_Supply_Negative"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid ""
"Validation failed because the resulting mosaic supply would be negative."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Mosaic_Supply_Exceeded"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "The provided mosaic supply is not in the range of 0 and 9.000.000.000."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Mosaic_Non_Transferable"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid ""
"Only the creator of the mosaic is eligible to be the recipient of a non-"
"transferable mosaic once transferred."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Transfer_Message_Too_Large"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "The message for the transaction exceeds the limit of ``1024`` bytes."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Transfer_Out_Of_Order_Mosaics"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Mosaics on a transfer transaction should be ordered by id value."
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Chain_Unlinked"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Chain_Block_Not_Hit"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Consumer_Empty_Input"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Consumer_Block_Transactions_Hash_Mismatch"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Consumer_Hash_In_Recency_Cache"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Consumer_Remote_Chain_Too_Many_Blocks"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Consumer_Remote_Chain_Improper_Link"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Consumer_Remote_Chain_Duplicate_Transactions"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Consumer_Remote_Chain_Unlinked"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Consumer_Remote_Chain_Mismatched_Difficulties"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Consumer_Remote_Chain_Score_Not_Better"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Consumer_Remote_Chain_Too_Far_Behind"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Extension_Partial_Transaction_Cache_Prune"
msgstr ""

#: ../../source/api/status-errors.rst:1
msgid "Failure_Extension_Partial_Transaction_Dependency_Removed"
msgstr ""
